env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  array-bracket-newline:
    - error
    - consistent
  brace-style:
    - error
    - stroustrup
  curly:
    - error
    - multi-line
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: first
      outerIIFEBody: 1
      MemberExpression: 1
      FunctionDeclaration:
        body: 1
        parameters: first
      FunctionExpression:
        body: 1
        parameters: first
      CallExpression:
        arguments: first
      ArrayExpression: first
      ObjectExpression: first
      ImportDeclaration: first
      flatTernaryExpressions: true
      offsetTernaryExpressions: true
      ignoreComments: false
  function-paren-newline:
    - error
    - multiline-arguments
  linebreak-style:
    - error
    - unix
  max-len:
    - warn
    - 120
  multiline-ternary:
    - error
    - always-multiline
  no-multi-spaces:
    - error
  no-trailing-spaces:
    - error
    - skipBlankLines: true
  object-curly-newline:
    - error
    - multiline: true
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  prefer-const:
    - warn
  quotes:
    - error
    - single
  react/jsx-closing-bracket-location:
    - error
    - tag-aligned
  react/jsx-closing-tag-location:
    - error
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-first-prop-new-line:
    - error
    - multiline
  react/jsx-max-props-per-line:
    - error
    - when: multiline
  react/jsx-newline:
    - error
    - prevent: true
      allowMultilines: true
  react/jsx-props-no-multi-spaces:
    - error
  react/jsx-tag-spacing:
    - error
    - closingSlash: never
      beforeSelfClosing: proportional-always
      afterOpening: never
      beforeClosing: proportional-always
  semi:
    - error
    - always
  space-in-parens:
    - error
    - never
